### ISSUE TITLE
[Bug]: Wrong Icon on Toggle theme button on initial page load

### ISSUE THREAD

**Issue by Zish303** [codeaashu/DevDisplay#87]
### What happened?

When the website loads, it opens in light mode by default. However, the toggle theme button have a icon of 'Sun' which should be in dark mode.
When we toggle the website from dark mode to light mode, then correct icon 'Moon' is shown.

Expected Behavior:
When the website loads and the theme is 'light', the toggle theme button should be 'Moon'.

### Add screenshots
Initial load
![image](https://github.com/user-attachments/assets/ef92112e-83e8-4c21-a09a-3e14942251ce)

Upon toggle from Dark mode to Light mode
![image](https://github.com/user-attachments/assets/52f93294-2559-4908-8d95-0ac545e391d0)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zish303** [comment]
Please add 'hacktoberfest' label to this issue, and I will start to solve the problem.

**Comment by itznayan** [comment]
please assign this issue to me .i am GSSOC'24 Extd Contributor and add nesessary tag for GSSOC contributor

**Comment by amanpoddar-dev12** [comment]
In the toggleTheme function, you update the theme by calling setTheme(), which likely updates a state variable theme. However, state updates in React are asynchronous. This means that when you call setTheme(), the change to the theme doesn't happen immediately but will be scheduled to occur after the component renders.
The icon does not change on the first click because the theme is still the old value during that initial render (before the state update has been fully completed.
![Screenshot 2024-10-03 063503](https://github.com/user-attachments/assets/7e807c24-9e93-4b06-8d3d-89a1dcf059b3)

you can see log theme is not updated before rendering that's why it gives same theme name.
If any one who have any idea to fix this bug please discuss here

**Comment by amanpoddar-dev12** [comment]
> please assign this issue to me .i am GSSOC'24 Extd Contributor and add nesessary tag for GSSOC contributor
this issue is  resolved please go ahead.
![Screenshot 2024-10-03 070815](https://github.com/user-attachments/assets/e0c82fd2-8c37-43de-b18c-af652bfcb20f)
check the logs
@Zish303 @itznayan

**Comment by Abhi0049k** [comment]
@Zish303 would like to work on this issue

**Comment by ishap11** [comment]
📢 Invitation to Join the DevDisplay WhatsApp Community!
We are excited to invite you to join the WhatsApp community of DevDisplay, where developers and contributors come together to collaborate and share their ideas.

**Collaborative Support:** If you are interested in working together with extensive support, we encourage you to join our community.

**Open Source Contribution:** If you would like to contribute to the DevDisplay open-source project, your participation is welcomed in our WhatsApp group.

By joining, you will have the opportunity to connect with like-minded individuals, discuss project developments, and contribute to our shared goals.
For more information and to join the community, please visit: [Join DevDisplay WhatsApp Community](https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4).

We look forward to your participation!
